// Code generated by "stringer -type=Status"; DO NOT EDIT.

package global

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusNil-0]
	_ = x[StatusWish-1]
	_ = x[StatusWatched-2]
	_ = x[StatusWatching-3]
	_ = x[StatusOnHold-4]
	_ = x[StatusDropped-5]
}

const _Status_name = "StatusNilStatusWishStatusWatchedStatusWatchingStatusOnHoldStatusDropped"

var _Status_index = [...]uint8{0, 9, 19, 32, 46, 58, 71}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
