// Code generated by "stringer -type=Type"; DO NOT EDIT.

package global

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeNil-0]
	_ = x[TypeAnime-1]
	_ = x[TypeMovie-2]
	_ = x[TypeGame-3]
	_ = x[TypeBook-4]
	_ = x[TypeMusic-5]
}

const _Type_name = "TypeNilTypeAnimeTypeMovieTypeGameTypeBookTypeMusic"

var _Type_index = [...]uint8{0, 7, 16, 25, 33, 41, 50}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
