basePath: /api
definitions:
  handler.AuthResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/model.UserInfo'
      msg:
        type: string
    type: object
  handler.BaseResponse:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  handler.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.UserInfo:
    properties:
      id:
        type: integer
      role:
        type: string
      username:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: unlicence
    url: http://unlicense.org/
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/islogin:
    get:
      consumes:
      - application/json
      description: Islogin
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.AuthResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.BaseResponse'
      summary: IsLogin
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: login info
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/handler.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.AuthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.BaseResponse'
      summary: login
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.BaseResponse'
      summary: logout
      tags:
      - auth
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
